import { ComponentMetadata } from './component-types';

export const COMPONENT_REGISTRY: Record<string, ComponentMetadata> = {
  StatusBadge: {
    componentId: 'StatusBadge',
    version: '1.0.0',
    lifecycleStage: 'production-approved',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=101:4',
    syncRiskLevel: 'low',
    auditTags: ['Unified/Badge', 'InterTypography', 'WCAG-AA-Pass'],
    lastAuditedAt: '2026-06-06',
  },
  PriorityBadge: {
    componentId: 'PriorityBadge',
    version: '1.0.0',
    lifecycleStage: 'production-approved',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=102:5',
    syncRiskLevel: 'low',
    auditTags: ['Unified/Badge', 'InterTypography', 'HighContrast'],
    lastAuditedAt: '2026-06-06',
  },
  OfflineSyncIndicator: {
    componentId: 'OfflineSyncIndicator',
    version: '1.0.0',
    lifecycleStage: 'validated',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=205:12',
    syncRiskLevel: 'low',
    auditTags: ['Unified/Indicator', 'OfflineSafety', 'RealtimeState'],
    lastAuditedAt: '2026-06-06',
  },
  MobileBottomNavigation: {
    componentId: 'MobileBottomNavigation',
    version: '1.0.0',
    lifecycleStage: 'production-approved',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=309:8',
    syncRiskLevel: 'medium',
    auditTags: ['Mobile/Routing', 'TouchTarget44', 'OneThumbNavigation'],
    lastAuditedAt: '2026-06-06',
  },
  ServiceCallCard: {
    componentId: 'ServiceCallCard',
    version: '1.0.0',
    lifecycleStage: 'production-approved',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=201:10',
    syncRiskLevel: 'medium',
    auditTags: ['Mobile/List', 'InterTypography', 'TouchTarget44'],
    lastAuditedAt: '2026-06-06',
  },
  DispatchKanbanCard: {
    componentId: 'DispatchKanbanCard',
    version: '1.0.0',
    lifecycleStage: 'production-approved',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=201:11',
    syncRiskLevel: 'medium',
    auditTags: ['Desktop/Widget', 'InterTypography', 'TouchTarget44'],
    lastAuditedAt: '2026-06-06',
  },
  DSInput: {
    componentId: 'DSInput',
    version: '1.0.0',
    lifecycleStage: 'validated',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=501:1',
    syncRiskLevel: 'low',
    auditTags: ['Form/Input', 'MobileFriendly', 'TouchTarget44'],
    lastAuditedAt: '2026-06-06',
  },
  DSTextarea: {
    componentId: 'DSTextarea',
    version: '1.0.0',
    lifecycleStage: 'validated',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=501:2',
    syncRiskLevel: 'low',
    auditTags: ['Form/Textarea', 'MobileFriendly', 'Resizable'],
    lastAuditedAt: '2026-06-06',
  },
  DSSelect: {
    componentId: 'DSSelect',
    version: '1.0.0',
    lifecycleStage: 'validated',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=501:3',
    syncRiskLevel: 'low',
    auditTags: ['Form/Select', 'MobileFriendly', 'TouchTarget44'],
    lastAuditedAt: '2026-06-06',
  },
  DSLabel: {
    componentId: 'DSLabel',
    version: '1.0.0',
    lifecycleStage: 'validated',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=501:4',
    syncRiskLevel: 'low',
    auditTags: ['Form/Label', 'Accessibility', 'InterTypography'],
    lastAuditedAt: '2026-06-06',
  },
  DSFormSection: {
    componentId: 'DSFormSection',
    version: '1.0.0',
    lifecycleStage: 'validated',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=501:5',
    syncRiskLevel: 'low',
    auditTags: ['Form/Section', 'Layout', 'CardWrapper'],
    lastAuditedAt: '2026-06-06',
  },
  DSValidationMessage: {
    componentId: 'DSValidationMessage',
    version: '1.0.0',
    lifecycleStage: 'validated',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=501:6',
    syncRiskLevel: 'low',
    auditTags: ['Form/Validation', 'Accessibility', 'AlertText'],
    lastAuditedAt: '2026-06-06',
  },
  DSBadge: {
    componentId: 'DSBadge',
    version: '1.0.0',
    lifecycleStage: 'validated',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=101:4',
    syncRiskLevel: 'low',
    auditTags: ['Unified/Badge', 'InterTypography', 'WCAG-AA-Pass'],
    lastAuditedAt: '2026-06-07',
  },
  DSCard: {
    componentId: 'DSCard',
    version: '1.0.0',
    lifecycleStage: 'production-approved',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=202:4',
    syncRiskLevel: 'low',
    auditTags: ['Unified/Card', 'Layout', 'InterTypography'],
    lastAuditedAt: '2026-06-08',
  },
  DSBottomNavigation: {
    componentId: 'DSBottomNavigation',
    version: '1.0.0',
    lifecycleStage: 'production-approved',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=310:1',
    syncRiskLevel: 'low',
    auditTags: ['Mobile/Navigation', 'TouchTarget48', 'OneThumbNavigation'],
    lastAuditedAt: '2026-06-08',
  },
  DSMobileHeader: {
    componentId: 'DSMobileHeader',
    version: '1.0.0',
    lifecycleStage: 'production-approved',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=310:2',
    syncRiskLevel: 'low',
    auditTags: ['Mobile/Header', 'TouchTarget48', 'Accessibility'],
    lastAuditedAt: '2026-06-08',
  },
  DSMobilePage: {
    componentId: 'DSMobilePage',
    version: '1.0.0',
    lifecycleStage: 'production-approved',
    figmaNodeMapping: 'figma.com/file/welo-ui?node-id=310:3',
    syncRiskLevel: 'low',
    auditTags: ['Mobile/Layout', 'SafeAreaSupport', 'KeyboardSafety'],
    lastAuditedAt: '2026-06-08',
  }
};
